language: php

php:
  - 7.1
  - 7.2
  - 7.3
  - 7.4

env:
  - DEPENDENCIES="--prefer-lowest --prefer-stable" PHP=""
  - DEPENDENCIES="--prefer-lowest --prefer-stable" PHP="ext/php-with-scoutapm.sh"
  - DEPENDENCIES="" PHP=""
  - DEPENDENCIES="" PHP="ext/php-with-scoutapm.sh"

install:
  - pecl install scoutapm

before_script:
  - composer self-update
  - rm composer.lock
  - composer update --prefer-dist $DEPENDENCIES

script:
  - $PHP vendor/bin/phpunit

jobs:
  include:
    - stage: Check coding standards
      php: 7.4
      env: DEPENDENCIES="" PHP=""
      script: vendor/bin/phpcs

    - stage: Run static analysis check
      php: 7.4
      env: DEPENDENCIES="" PHP=""
      script: vendor/bin/psalm

notifications:
  on_success: never
  on_failure: always
