language: php

php:
  - 7.1
  - 7.2
  - 7.3

before_script:
  - composer self-update
  - composer install --prefer-dist --no-interaction --no-suggest

jobs:
  include:
    - stage: Check coding standards
      script: vendor/bin/phpcs

    - stage: Run static analysis check
      script: vendor/bin/psalm

    - stage: Test
      script: vendor/bin/phpunit

notifications:
  on_success: never
  on_failure: always
