name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  tests:
    name: "Run tests"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dependencies: ["lowest", "highest"]
        extensions: ["scoutapm", ""]
        php-version:
          - "7.1"
          - "7.2"
          - "7.3"
          - "7.4"
          - "8.0"
    env:
      SCOUT_APM_KEY: ${{ secrets.SCOUT_APM_KEY }}
    steps:
      - uses: actions/checkout@v2
      - name: "Install PHP"
        uses: shivammathur/setup-php@v2
        with:
          coverage: "none"
          php-version: "${{ matrix.php-version }}"
          tools: pecl
          extensions: ${{ matrix.extensions }}
      - name: "Install lowest dependencies"
        if: ${{ matrix.dependencies == 'lowest' }}
        run: "composer update --prefer-lowest --prefer-dist --no-interaction --no-progress"
      - name: "Install highest dependencies"
        if: ${{ matrix.dependencies == 'highest' }}
        run: "composer update --prefer-dist --no-interaction --no-progress"
      - name: "Run PHPUnit test suite"
        run: "vendor/bin/phpunit"
      - name: "Check for memory leaks"
        run: "tests/check-memory-leaks.sh"

  framework-unit-tests:
    name: "Framework Tests"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        extensions: ["scoutapm", ""]
        framework-version:
          - "laravel/framework:5.5.*"
          - "laravel/framework:6.*"
          - "laravel/framework:7.*"
          - "laravel/framework:8.*"
        php-version:
          - "7.1"
          - "7.2"
          - "7.3"
          - "7.4"
          - "8.0"
        exclude:
          - {php-version: "7.1", framework-version: "laravel/framework:6.*"} # Laravel 6 requires 7.2+
          - {php-version: "7.1", framework-version: "laravel/framework:7.*"} # Laravel 7 requires 7.2+
          - {php-version: "7.1", framework-version: "laravel/framework:8.*"} # Laravel 8 requires 7.3+
          - {php-version: "7.2", framework-version: "laravel/framework:8.*"} # Laravel 8 requires 7.3+
    steps:
      - uses: actions/checkout@v2
      - name: "Install PHP"
        uses: shivammathur/setup-php@v2
        with:
          coverage: "none"
          php-version: "${{ matrix.php-version }}"
          tools: pecl
          extensions: ${{ matrix.extensions }}
      # --no-update then a full `composer update` is needed to overcome locked dependencies
      # See: https://github.com/composer/composer/issues/9561
      - name: "Require framework ${{ matrix.framework-version}}"
        run: "composer require ${{ matrix.framework-version}} --no-update --no-interaction --prefer-dist --prefer-stable"
      - name: "Composer update with new requirements"
        run: "composer update --no-interaction --prefer-dist --prefer-stable"
      - name: "Run PHPUnit test suite"
        run: "vendor/bin/phpunit"

  laravel-e2e:
    name: "Laravel End-to-End Test"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        extensions: ["scoutapm", ""]
        laravel-version:
          - "5.5.*"
          - "6.*"
          - "7.*"
          - "8.*"
        php-version:
          - "7.1"
          - "7.2"
          - "7.3"
          - "7.4"
        exclude:
          - {php-version: "7.1", laravel-version: "6.*"} # Laravel 6 requires 7.2+
          - {php-version: "7.1", laravel-version: "7.*"} # Laravel 7 requires 7.2+
          - {php-version: "7.1", laravel-version: "8.*"} # Laravel 8 requires 7.3+
          - {php-version: "7.2", laravel-version: "8.*"} # Laravel 8 requires 7.3+
    env:
      SCOUT_APM_KEY: ${{ secrets.SCOUT_APM_KEY }}
    steps:
      - uses: actions/checkout@v2
        with:
          path: scout-apm-php
      - name: "Install PHP"
        uses: shivammathur/setup-php@v2
        with:
          coverage: "none"
          php-version: "${{ matrix.php-version }}"
          tools: pecl
          extensions: ${{ matrix.extensions }}
      - name: "Install Laravel quickstart project"
        run: "composer create-project laravel/laravel:${{ matrix.laravel-version}} test-app --prefer-dist"
      - name: "Add scout-apm-php as a repository"
        run: cd test-app && composer config repositories.scout path ../scout-apm-php
      - name: "Require scout-apm-php current checkout"
        run: cd test-app && composer require scoutapp/scout-apm-php:*@dev composer/package-versions-deprecated
      - name: "Publish the provider"
        run: cd test-app && php artisan vendor:publish --provider="Scoutapm\Laravel\Providers\ScoutApmServiceProvider"
      - name: "Configure Scout"
        run: cd test-app && echo -e "\nSCOUT_KEY=\"\${SCOUT_APM_KEY}\"\nSCOUT_NAME=\"My Laravel App\"\nSCOUT_MONITOR=true" >> .env
      - name: "Load the index page to trigger instrumentation"
        run: |
          cd test-app
          cat .env
          php artisan serve &
          sleep 2
          wget http://localhost:8000
      - name: "Check logs for successful payload send"
        run: |
          cd test-app
          cat storage/logs/laravel.log
          grep -q "local.DEBUG: \[Scout\] Sent whole payload successfully to core agent." storage/logs/laravel.log

  cs:
    name: "Check coding standards"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: "Install PHP"
        uses: shivammathur/setup-php@v2
        with:
          coverage: "none"
          php-version: "8.0"
      - name: "Install dependencies"
        run: "composer install"
      - name: "Run PHP_CodeSniffer"
        run: "vendor/bin/phpcs"

  static-analysis:
    name: "Perform static analysis"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: "Install PHP"
        uses: shivammathur/setup-php@v2
        with:
          coverage: "none"
          php-version: "8.0"
      - name: "Install dependencies"
        run: "composer install"
      - name: "Run Psalm"
        run: "vendor/bin/psalm"

  roave-backwards-compatibility-check:
    name: "Check for Backward Compatibility breaks"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: "Install PHP"
        uses: shivammathur/setup-php@v2
        with:
          coverage: "none"
          php-version: "7.4" # https://github.com/Roave/BackwardCompatibilityCheck/issues/283
      - name: "Require Roave/BackwardCompatibilityCheck"
        run: "composer require --no-update --no-interaction --prefer-dist --prefer-stable --dev roave/backward-compatibility-check"
      - name: "Composer update with new requirements"
        run: "composer update --no-interaction --prefer-dist --prefer-stable"
      - name: "Check for BC breaks"
        run: "vendor/bin/roave-backward-compatibility-check --format=markdown"
