name: Quality Checks

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: '37 9 1 * *'

jobs:
  cs:
    name: "Check coding standards"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: "Install PHP"
        uses: shivammathur/setup-php@v2
        with:
          coverage: "none"
          php-version: "8.0"
      - name: "Install dependencies"
        run: "composer install"
      - name: "Run PHP_CodeSniffer"
        run: "vendor/bin/phpcs"

  static-analysis:
    name: "Perform static analysis"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: "Install PHP"
        uses: shivammathur/setup-php@v2
        with:
          coverage: "none"
          php-version: "8.0"
      - name: "Install dependencies"
        run: "composer install"
      - name: "Run Psalm"
        run: "vendor/bin/psalm"

# Disabled for now... - see https://github.com/scoutapp/scout-apm-php/issues/209
#  roave-backwards-compatibility-check:
#    name: "Check for Backward Compatibility breaks"
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v2
#        with:
#          fetch-depth: 0
#      - name: "Install PHP"
#        uses: shivammathur/setup-php@v2
#        with:
#          coverage: "none"
#          php-version: "7.4" # https://github.com/Roave/BackwardCompatibilityCheck/issues/283
#      - name: "Require Roave/BackwardCompatibilityCheck"
#        run: "composer require --no-update --no-interaction --prefer-dist --prefer-stable --dev roave/backward-compatibility-check"
#      - name: "Composer update with new requirements"
#        run: "composer update --no-interaction --prefer-dist --prefer-stable"
#      - name: "Check for BC breaks"
#        run: "vendor/bin/roave-backward-compatibility-check --format=markdown"
